#数据才有类型，变量没有类型
#我们可以通过type()来判断数据类型
a=1.1
print(type(a))
b=1
print(type(b))
c="nis"
print(type(c))
d=["1","ss"]
print(type(d))
e={
    "key":"value",
    "age":"11"
}
print(type(e))
f=True
print(type(f))
#总而言之，我们主要学习了如何判断变量数据类型，通过type（变量名）